// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// potential_radiation_cr
float potential_radiation_cr(int hour, int minute, int yday, float lon, float lat, float timezone);
RcppExport SEXP _metGeneratoR_potential_radiation_cr(SEXP hourSEXP, SEXP minuteSEXP, SEXP ydaySEXP, SEXP lonSEXP, SEXP latSEXP, SEXP timezoneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type hour(hourSEXP);
    Rcpp::traits::input_parameter< int >::type minute(minuteSEXP);
    Rcpp::traits::input_parameter< int >::type yday(ydaySEXP);
    Rcpp::traits::input_parameter< float >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< float >::type lat(latSEXP);
    Rcpp::traits::input_parameter< float >::type timezone(timezoneSEXP);
    rcpp_result_gen = Rcpp::wrap(potential_radiation_cr(hour, minute, yday, lon, lat, timezone));
    return rcpp_result_gen;
END_RCPP
}
// HourlyT_cr
NumericVector HourlyT_cr(int nrec, double TminHour, double Tmin, double TmaxHour, double Tmax);
RcppExport SEXP _metGeneratoR_HourlyT_cr(SEXP nrecSEXP, SEXP TminHourSEXP, SEXP TminSEXP, SEXP TmaxHourSEXP, SEXP TmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrec(nrecSEXP);
    Rcpp::traits::input_parameter< double >::type TminHour(TminHourSEXP);
    Rcpp::traits::input_parameter< double >::type Tmin(TminSEXP);
    Rcpp::traits::input_parameter< double >::type TmaxHour(TmaxHourSEXP);
    Rcpp::traits::input_parameter< double >::type Tmax(TmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(HourlyT_cr(nrec, TminHour, Tmin, TmaxHour, Tmax));
    return rcpp_result_gen;
END_RCPP
}
// set_vp_cr
NumericVector set_vp_cr(NumericVector tair_r, NumericVector relhum_r, int nx, int ny, int nrec);
RcppExport SEXP _metGeneratoR_set_vp_cr(SEXP tair_rSEXP, SEXP relhum_rSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP nrecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tair_r(tair_rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relhum_r(relhum_rSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< int >::type nrec(nrecSEXP);
    rcpp_result_gen = Rcpp::wrap(set_vp_cr(tair_r, relhum_r, nx, ny, nrec));
    return rcpp_result_gen;
END_RCPP
}
// sh2vp
NumericVector sh2vp(NumericVector q, NumericVector p);
RcppExport SEXP _metGeneratoR_sh2vp(SEXP qSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(sh2vp(q, p));
    return rcpp_result_gen;
END_RCPP
}
// set_min_max_hour_cr
NumericVector set_min_max_hour_cr(NumericVector radfrac, int nx);
RcppExport SEXP _metGeneratoR_set_min_max_hour_cr(SEXP radfracSEXP, SEXP nxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type radfrac(radfracSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    rcpp_result_gen = Rcpp::wrap(set_min_max_hour_cr(radfrac, nx));
    return rcpp_result_gen;
END_RCPP
}
// set_max_min_lonlat_cr
NumericVector set_max_min_lonlat_cr(NumericVector tmin_map, NumericVector tmax_map, int yday, int nrec, NumericVector lonlatbox);
RcppExport SEXP _metGeneratoR_set_max_min_lonlat_cr(SEXP tmin_mapSEXP, SEXP tmax_mapSEXP, SEXP ydaySEXP, SEXP nrecSEXP, SEXP lonlatboxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tmin_map(tmin_mapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax_map(tmax_mapSEXP);
    Rcpp::traits::input_parameter< int >::type yday(ydaySEXP);
    Rcpp::traits::input_parameter< int >::type nrec(nrecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lonlatbox(lonlatboxSEXP);
    rcpp_result_gen = Rcpp::wrap(set_max_min_lonlat_cr(tmin_map, tmax_map, yday, nrec, lonlatbox));
    return rcpp_result_gen;
END_RCPP
}
// rad_map_final_cr
NumericVector rad_map_final_cr(int nrec, int yday, double gmt_float, NumericVector lonlatbox);
RcppExport SEXP _metGeneratoR_rad_map_final_cr(SEXP nrecSEXP, SEXP ydaySEXP, SEXP gmt_floatSEXP, SEXP lonlatboxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrec(nrecSEXP);
    Rcpp::traits::input_parameter< int >::type yday(ydaySEXP);
    Rcpp::traits::input_parameter< double >::type gmt_float(gmt_floatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lonlatbox(lonlatboxSEXP);
    rcpp_result_gen = Rcpp::wrap(rad_map_final_cr(nrec, yday, gmt_float, lonlatbox));
    return rcpp_result_gen;
END_RCPP
}
// rad_map_lats_cr
NumericVector rad_map_lats_cr(int nt, int yday);
RcppExport SEXP _metGeneratoR_rad_map_lats_cr(SEXP ntSEXP, SEXP ydaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< int >::type yday(ydaySEXP);
    rcpp_result_gen = Rcpp::wrap(rad_map_lats_cr(nt, yday));
    return rcpp_result_gen;
END_RCPP
}
// solar_geom_cr
NumericVector solar_geom_cr(float lat, int yday, int timesteps_per_day);
RcppExport SEXP _metGeneratoR_solar_geom_cr(SEXP latSEXP, SEXP ydaySEXP, SEXP timesteps_per_daySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type lat(latSEXP);
    Rcpp::traits::input_parameter< int >::type yday(ydaySEXP);
    Rcpp::traits::input_parameter< int >::type timesteps_per_day(timesteps_per_daySEXP);
    rcpp_result_gen = Rcpp::wrap(solar_geom_cr(lat, yday, timesteps_per_day));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metGeneratoR_potential_radiation_cr", (DL_FUNC) &_metGeneratoR_potential_radiation_cr, 6},
    {"_metGeneratoR_HourlyT_cr", (DL_FUNC) &_metGeneratoR_HourlyT_cr, 5},
    {"_metGeneratoR_set_vp_cr", (DL_FUNC) &_metGeneratoR_set_vp_cr, 5},
    {"_metGeneratoR_sh2vp", (DL_FUNC) &_metGeneratoR_sh2vp, 2},
    {"_metGeneratoR_set_min_max_hour_cr", (DL_FUNC) &_metGeneratoR_set_min_max_hour_cr, 2},
    {"_metGeneratoR_set_max_min_lonlat_cr", (DL_FUNC) &_metGeneratoR_set_max_min_lonlat_cr, 5},
    {"_metGeneratoR_rad_map_final_cr", (DL_FUNC) &_metGeneratoR_rad_map_final_cr, 4},
    {"_metGeneratoR_rad_map_lats_cr", (DL_FUNC) &_metGeneratoR_rad_map_lats_cr, 2},
    {"_metGeneratoR_solar_geom_cr", (DL_FUNC) &_metGeneratoR_solar_geom_cr, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_metGeneratoR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
