# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rad_map_final_cr <- function(nrec, yday, nx_parts) {
    .Call('_metGeneratoR_rad_map_final_cr', PACKAGE = 'metGeneratoR', nrec, yday, nx_parts)
}

rad_map_lats_cr <- function(nt, yday) {
    .Call('_metGeneratoR_rad_map_lats_cr', PACKAGE = 'metGeneratoR', nt, yday)
}

solar_geom_cr <- function(lat, yday, timesteps_per_day) {
    .Call('_metGeneratoR_solar_geom_cr', PACKAGE = 'metGeneratoR', lat, yday, timesteps_per_day)
}

timesTwo <- function(x) {
    .Call('_metGeneratoR_timesTwo', PACKAGE = 'metGeneratoR', x)
}

