# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_vp_cr <- function(tair_r, relhum_r, nx, ny, nrec) {
    .Call('_metGeneratoR_set_vp_cr', PACKAGE = 'metGeneratoR', tair_r, relhum_r, nx, ny, nrec)
}

sh2vp <- function(q, p) {
    .Call('_metGeneratoR_sh2vp', PACKAGE = 'metGeneratoR', q, p)
}

set_min_max_hour_cr <- function(radfrac, nx) {
    .Call('_metGeneratoR_set_min_max_hour_cr', PACKAGE = 'metGeneratoR', radfrac, nx)
}

calc_tas_cr <- function(rad_fract_map, tmin_map, tmax_map, yday, nrec, xybox) {
    .Call('_metGeneratoR_calc_tas_cr', PACKAGE = 'metGeneratoR', rad_fract_map, tmin_map, tmax_map, yday, nrec, xybox)
}

#' @export
rad_map_final_cr <- function(nrec, yday, gmt_float, xybox, lats, lons, gmt_offset) {
    .Call('_metGeneratoR_rad_map_final_cr', PACKAGE = 'metGeneratoR', nrec, yday, gmt_float, xybox, lats, lons, gmt_offset)
}

rad_map_lats_cr <- function(nt, yday) {
    .Call('_metGeneratoR_rad_map_lats_cr', PACKAGE = 'metGeneratoR', nt, yday)
}

solar_geom_cr <- function(lat, yday, timesteps_per_day) {
    .Call('_metGeneratoR_solar_geom_cr', PACKAGE = 'metGeneratoR', lat, yday, timesteps_per_day)
}

