# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_vp_cr <- function(tair_r, relhum_r, nx, ny, nrec) {
    .Call('_metGeneratoR_set_vp_cr', PACKAGE = 'metGeneratoR', tair_r, relhum_r, nx, ny, nrec)
}

set_min_max_hour_cr <- function(radfrac, nx) {
    .Call('_metGeneratoR_set_min_max_hour_cr', PACKAGE = 'metGeneratoR', radfrac, nx)
}

set_max_min_lonlat_cr <- function(tmin_map, tmax_map, yday, nrec) {
    .Call('_metGeneratoR_set_max_min_lonlat_cr', PACKAGE = 'metGeneratoR', tmin_map, tmax_map, yday, nrec)
}

rad_map_final_cr <- function(nrec, yday, nx_parts, gmt_float) {
    .Call('_metGeneratoR_rad_map_final_cr', PACKAGE = 'metGeneratoR', nrec, yday, nx_parts, gmt_float)
}

rad_map_lats_cr <- function(nt, yday) {
    .Call('_metGeneratoR_rad_map_lats_cr', PACKAGE = 'metGeneratoR', nt, yday)
}

solar_geom_cr <- function(lat, yday, timesteps_per_day) {
    .Call('_metGeneratoR_solar_geom_cr', PACKAGE = 'metGeneratoR', lat, yday, timesteps_per_day)
}

